_inputs:
  cover:
    type: image
  src:
    type: image
  _author:
    type: select
    options:
      values:
        - Redacción TYSM
        - Francisco Massé
        
        
        
_snippets_imports:
  mdx: true
