
_inputs:
  cover:
    type: image
  src:
    type: image
  author:
    type: select
    options:
      values:
        - Redacción TYSM
  show_author_profile: false
  comment:
    hidden: true
  sharing:
    hidden: true
  layout: 
    hidden: true
  mode:
    hidden: true
  excerpt_separator:
    hidden: true
  header:
    hidden: true
          
_snippets_imports:
  mdx: true
