_inputs:
  cover:
    type: image
  src:
    type: image
  author:
    type: select
    hidden: true
    options:
      values:
        - Redacción TYSM
        - Francisco Massé
  mode:
    default: dark
        
        
        
_snippets_imports:
  mdx: true
