_inputs:
  cover:
    type: image
  src:
    type: image
  author:
    type: select
    options:
      values:
        - Redacción TYSM
        - Francisco Massé
  mode:
    text: dark
  _show_author_profile:
  
        
_snippets_imports:
  mdx: true
