_inputs:
  cover:
    type: image
  src:
    type: image
  author:
    type: select
    options:
      values:
        - Redacción TYSM
        - Francisco Massé
        
        
# Import the Eleventy Nunjucks Snippets:
_snippets_imports:
  eleventy_nunjucks: true

# Import the Eleventy Liquid Snippets:
_snippets_imports:
  eleventy_liquid: true
