_inputs:
  cover:
    type: image
  src:
    type: image
  author:
    type: select
    options:
      values:
        - Redacción TYSM
        - Francisco Massé
  mode: dark
        
        
_snippets_imports:
  mdx: true
